require("caiomarxm.functionalities.nvimtree")
require("caiomarxm.functionalities.lspconfig")
require("caiomarxm.functionalities.treesitter")
require("caiomarxm.functionalities.dap")
require("caiomarxm.functionalities.autotag")
